config/routes.rb
Rails.application.routes.draw do

  get 'event/stripe_callback'

  get 'event/payment_profile'

  resources :tenant_fees
  resources :admin_costs
  resources :accounts
  resources :rates
  resources :banks
  resources :microdeposits
  
  authenticated :user do
    root to: "accounts#show", as: :authenticated_root
  end

  root to: "static_pages#details"


  resources :sites
  devise_for :users, controllers: {registrations:'users/registrations'}
  resources :users
  resources :payments
  resources :charges
  resources :spaces do 
    member do
      get 'get_meters'
    end
  end

  get "eula", to: "accounts#eula"

  get "everest", to: "static_pages#everest"
  get "pricing", to: "static_pages#pricing"
  get "details", to: "static_pages#details"
  get "beta", to: "static_pages#beta"
  get "for-tenants", to: "static_pages#tenants"

  get "meter-setup", to: "billable_meters#configure"
  get "billable_meters/reload_configured_list", to: "billable_meters#reload_configured_list"

  get "stripe/connect", to:"accounts#stripe_callback", as: :stripe_connect

  resources :contacts
  resources :billable_meters
  resources :meters
  resources :invoices
  resources :tenants
  resources :records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/tenant_sign_up/:acct_id/:id", to: "tenants#sign_up"
  post "/accounts/:id/update_billing_day", to: "accounts#update_billing_day"  
  post "/accounts/:id/update_days_until_invoice_due", to: "accounts#update_days_until_invoice_due"
  resources :messages, only: [:new, :create]
  get "/signed_up", to: "messages#complete"
  get "/sign_up", to: "messages#new"
  post "/sign_up", to: "messages#create"
  
  #api
  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create, :show]
      resources :users, only: [:show] 
      get 'meters', to: 'users#meters'
      post 'meters', to: 'meters#import'
      post 'records', to: 'records#import'
      resources :billable_meters, only: [:index]
      resources :records, only: [:create]
    end
  end  
end

app/models/admin_cost.rb
class AdminCost < ApplicationRecord
  belongs_to :account
  # validates :percent, numericality: {greater_than: 0}
end

app/controllers/admin_costs_controller.rb
class AdminCostsController < ApplicationController
  before_action :set_admin_cost, only: [:show, :edit, :update, :destroy]

  # GET /admin_costs
  # GET /admin_costs.json
  def index
    @admin_costs = AdminCost.all
  end

  # GET /admin_costs/1
  # GET /admin_costs/1.json
  def show
  end

  # GET /admin_costs/new
  def new
    @admin_cost = AdminCost.new
  end

  # GET /admin_costs/1/edit
  def edit
  end

  # POST /admin_costs
  # POST /admin_costs.json
  def create
    amount = params[:admin_cost][:amount]
    label = params[:admin_cost][:label]
    description = params[:admin_cost][:description]
    account_id = params[:admin_cost][:account_id]
    percent = nil
    flat_fee = nil

    if (amount)
      if (amount.include?("%"))
        percent = amount.delete('$ , %')
      else
        flat_fee = amount.delete('$ , %')
      end
    end

    @admin_cost = AdminCost.new(label: label, percent: percent, flat_fee: flat_fee, description: description, account_id: account_id)

    noticeText=""
    if (@admin_cost.save)
      noticeText = @admin_cost.label + " was successfully added."
    else
      noticeText = @admin_cost.errors
    end
    redirect_back(fallback_location: root_path,notice: noticeText)
  end

  # PATCH/PUT /admin_costs/1
  # PATCH/PUT /admin_costs/1.json
  def update
    respond_to do |format|
      if @admin_cost.update(admin_cost_params)
        format.html { redirect_to @admin_cost, notice: 'Admin cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_cost }
      else
        format.html { render :edit }
        format.json { render json: @admin_cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_costs/1
  # DELETE /admin_costs/1.json
  def destroy
    noticeText = @admin_cost.label + " was successfully removed."
    @admin_cost.destroy
    redirect_back(fallback_location: root_path,notice: noticeText)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_cost
      @admin_cost = AdminCost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_cost_params
      params.require(:admin_cost).permit(:label, :description, :percent, :flat_fee, :account_id)
    end
end

app/helpers/admin_costs_helper.rb
module AdminCostsHelper
end

app/views/admin_costs/_account_list.html.erb
<div class="col-md-1"></div>
  <div class="">          
    <h3>Admin Costs</h3>
      <div class="table-header-row">
        <div class='table-row-item admin-cost-item'>
          <div class="table-cell label">Label</div>
          <div class="table-cell amount">Rate</div>
          <div class="table-cell description">Description</div>
          <div class="table-cell link">Delete</div>          
        </div>
      </div>
    <div id="rate-list">
      <div class="table h-100">
        <% 
        if (admin_costs != nil)
          admin_costs.each do |cost| 
            amount=nil
            if (cost.percent?)
              amount = cost.percent.to_s + "%"
            else
              amount = "$" + cost.flat_fee.to_s
            end
            %>
            <div class="table-row">
              <div class='table-row-item admin-cost-item'>
                <div class="table-cell label"><%= cost.label %></div>
                <div class="table-cell amount"><%= amount %></div>
                <div class="table-cell description"><%= cost.description %></div>
                <div class="table-cell link"><%= link_to '✕', cost, method: :delete, data: { confirm: "Are you sure you would like to remove this admin cost?" } %></div>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="table-row">
          <div class='table-row-item admin-cost-item'>
            <% cost = AdminCost.new %>
            <%= form_with(model: cost, local: true) do |form| %>

              <div class="inline-field table-cell label">
                <%= form.label :label, class: "sr-only" %>
                <%= form.text_field :label, id: :cost_label, required: true, placeholder: "Label" %>
              </div>

              <div class="inline-field table-cell amount">
                <%= form.label :amount, class: "sr-only"  %>
                <%= form.text_field :amount, id: :cost_percent, onkeypress:"return isNumberKey(event)", placeholder: "\% Fee" %>
              </div>

              <div class="inline-field table-cell description">
                <%= form.label :description, class: "sr-only"  %>
                <%= form.text_field :description, id: :cost_description, placeholder: "Description" %>
              </div>

              <%= form.hidden_field :account_id, :value => @account.id %>

              <div class="actions inline-field table-cell link">
                <%= form.submit class: "btn-primary", value: "Add" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    function isNumberKey(evt)
       {
          // var charCode = (evt.which) ? evt.which : evt.keyCode;
          // if (charCode != 46 && charCode > 31 
          //   && (charCode < 48 || charCode > 57))
          //    return false;

          // return true;
       }
  </script>

app/views/admin_costs/_form.html.erb
<%= form_with(model: admin_cost, local: true) do |form| %>
  <% if admin_cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_cost.errors.count, "error") %> prohibited this admin_cost from being saved:</h2>

      <ul>
      <% admin_cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label, id: :admin_cost_label %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :admin_cost_description %>
  </div>

  <div class="field">
    <%= form.label :percent %>
    <%= form.text_field :percent, id: :admin_cost_percent %>
  </div>

  <div class="field">
    <%= form.label :flat_fee %>
    <%= form.text_field :flat_fee, id: :admin_cost_flat_fee %>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.text_field :account_id, id: :admin_cost_account_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_costs/edit.html.erb
<h1>Editing Admin Cost</h1>

<%= render 'form', admin_cost: @admin_cost %>

<%= link_to 'Show', @admin_cost %> |
<%= link_to 'Back', admin_costs_path %>

app/views/admin_costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Costs</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Description</th>
      <th>Percent</th>
      <th>Flat fee</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_costs.each do |admin_cost| %>
      <tr>
        <td><%= admin_cost.label %></td>
        <td><%= admin_cost.description %></td>
        <td><%= admin_cost.percent %></td>
        <td><%= admin_cost.flat_fee %></td>
        <td><%= admin_cost.account %></td>
        <td><%= link_to 'Show', admin_cost %></td>
        <td><%= link_to 'Edit', edit_admin_cost_path(admin_cost) %></td>
        <td><%= link_to 'Destroy', admin_cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Cost', new_admin_cost_path %>

app/views/admin_costs/new.html.erb
<h1>New Admin Cost</h1>

<%= render 'form', admin_cost: @admin_cost %>

<%= link_to 'Back', admin_costs_path %>

app/views/admin_costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @admin_cost.label %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_cost.description %>
</p>

<p>
  <strong>Percent:</strong>
  <%= @admin_cost.percent %>
</p>

<p>
  <strong>Flat fee:</strong>
  <%= @admin_cost.flat_fee %>
</p>

<p>
  <strong>Account:</strong>
  <%= @admin_cost.account %>
</p>

<%= link_to 'Edit', edit_admin_cost_path(@admin_cost) %> |
<%= link_to 'Back', admin_costs_path %>