config/routes.rb
Rails.application.routes.draw do

  get 'event/stripe_callback'

  get 'event/payment_profile'

  resources :tenant_fees
  resources :admin_costs
  resources :accounts
  resources :rates
  resources :banks
  resources :microdeposits
  
  authenticated :user do
    root to: "accounts#show", as: :authenticated_root
  end

  root to: "static_pages#details"


  resources :sites
  devise_for :users, controllers: {registrations:'users/registrations'}
  resources :users
  resources :payments
  resources :charges
  resources :spaces do 
    member do
      get 'get_meters'
    end
  end

  get "eula", to: "accounts#eula"

  get "everest", to: "static_pages#everest"
  get "pricing", to: "static_pages#pricing"
  get "details", to: "static_pages#details"
  get "beta", to: "static_pages#beta"
  get "for-tenants", to: "static_pages#tenants"

  get "meter-setup", to: "billable_meters#configure"
  get "billable_meters/reload_configured_list", to: "billable_meters#reload_configured_list"

  get "stripe/connect", to:"accounts#stripe_callback", as: :stripe_connect

  resources :contacts
  resources :billable_meters
  resources :meters
  resources :invoices
  resources :tenants
  resources :records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/tenant_sign_up/:acct_id/:id", to: "tenants#sign_up"
  post "/accounts/:id/update_billing_day", to: "accounts#update_billing_day"  
  post "/accounts/:id/update_days_until_invoice_due", to: "accounts#update_days_until_invoice_due"
  resources :messages, only: [:new, :create]
  get "/signed_up", to: "messages#complete"
  get "/sign_up", to: "messages#new"
  post "/sign_up", to: "messages#create"
  
  #api
  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create, :show]
      resources :users, only: [:show] 
      get 'meters', to: 'users#meters'
      post 'meters', to: 'meters#import'
      post 'records', to: 'records#import'
      resources :billable_meters, only: [:index]
      resources :records, only: [:create]
    end
  end  
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :tenant
  belongs_to :invoice
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:date, :amount, :tenant_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(payment) do |f| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :tenant_id %>
    <%= f.text_field :tenant_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
      <th>Tenant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.date %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.tenant %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @payment.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Tenant:</strong>
  <%= @payment.tenant %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>