config/routes.rb
Rails.application.routes.draw do

  get 'event/stripe_callback'

  get 'event/payment_profile'

  resources :tenant_fees
  resources :admin_costs
  resources :accounts
  resources :rates
  resources :banks
  resources :microdeposits
  
  authenticated :user do
    root to: "accounts#show", as: :authenticated_root
  end

  root to: "static_pages#details"


  resources :sites
  devise_for :users, controllers: {registrations:'users/registrations'}
  resources :users
  resources :payments
  resources :charges
  resources :spaces do 
    member do
      get 'get_meters'
    end
  end

  get "eula", to: "accounts#eula"

  get "everest", to: "static_pages#everest"
  get "pricing", to: "static_pages#pricing"
  get "details", to: "static_pages#details"
  get "beta", to: "static_pages#beta"
  get "for-tenants", to: "static_pages#tenants"

  get "meter-setup", to: "billable_meters#configure"
  get "billable_meters/reload_configured_list", to: "billable_meters#reload_configured_list"

  get "stripe/connect", to:"accounts#stripe_callback", as: :stripe_connect

  resources :contacts
  resources :billable_meters
  resources :meters
  resources :invoices
  resources :tenants
  resources :records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/tenant_sign_up/:acct_id/:id", to: "tenants#sign_up"
  post "/accounts/:id/update_billing_day", to: "accounts#update_billing_day"  
  post "/accounts/:id/update_days_until_invoice_due", to: "accounts#update_days_until_invoice_due"
  resources :messages, only: [:new, :create]
  get "/signed_up", to: "messages#complete"
  get "/sign_up", to: "messages#new"
  post "/sign_up", to: "messages#create"
  
  #api
  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create, :show]
      resources :users, only: [:show] 
      get 'meters', to: 'users#meters'
      post 'meters', to: 'meters#import'
      post 'records', to: 'records#import'
      resources :billable_meters, only: [:index]
      resources :records, only: [:create]
    end
  end  
end

app/views/navigation/_menu.html.erb
<div class="hide full-screen-menu" onclick="toggleMenu();">
    <div class="menu-logo float-left">
      <a href="<%= root_path %>"><%= image_tag 'logo-white.png' %></a>
    </div>
    <ul class="menu">      
        <% if user_signed_in? %>
          <li class="menu-item"><%= link_to('Home', root_path) %></li>
          <li class="menu-item"><%= link_to('Account', edit_account_path(current_user.account)) %></li>
          <li class="menu-item"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li class="menu-item"><%= link_to('Sign Up', sign_up_path)  %></li>
          <li class="menu-item"><%= link_to('Login', new_user_session_path)  %></li>
        <% end %>
        <li class="menu-item-small"><%= link_to('About', "#")  %></li>
        <li class="menu-item-small"><%= link_to('Support', "#")  %></li>
        <li class="menu-item-small"><%= link_to('Contact', "#")  %></li>
    </ul>
</div>

app/views/navigation/_nav.html.erb
<nav class="navbar-fixed navbar-light">
  <div id="notices"></div>
  <a href="<%= root_path %>" id="title">
    <%= image_tag "header-logo.png" %>
    <!-- <span>ELLY</span> -->
  </a>
  <% unless controller_name == "sessions" && action_name == "new" || controller_name == "accounts" && action_name == "eula" %>
        
    <% if current_user != nil && !current_user.tenant? %>
      <span id='vertical-menu-separator'>|</span>
      <a class="static-menu-item" href="<%= tenants_path %>">Tenants</a>
      <a class="static-menu-item" href="<%= invoices_path %>">Invoices</a>
      <a class="static-menu-item" href="<%= meter_setup_url %>">Meters</a>
      <a class="static-menu-item" href="<%= tenant_fees_path %>">Fees</a>
    <% end %>
    
    <button class="navbar-toggler ml-auto hidden-sm-up float-xs-right" onclick="toggleMenu();" >
      <span class="navbar-toggler-icon"></span>
    </button>

  <% end %>

</nav>