config/routes.rb
Rails.application.routes.draw do

  get 'event/stripe_callback'

  get 'event/payment_profile'

  resources :tenant_fees
  resources :admin_costs
  resources :accounts
  resources :rates
  resources :banks
  resources :microdeposits
  
  authenticated :user do
    root to: "accounts#show", as: :authenticated_root
  end

  root to: "static_pages#details"


  resources :sites
  devise_for :users, controllers: {registrations:'users/registrations'}
  resources :users
  resources :payments
  resources :charges
  resources :spaces do 
    member do
      get 'get_meters'
    end
  end

  get "eula", to: "accounts#eula"

  get "everest", to: "static_pages#everest"
  get "pricing", to: "static_pages#pricing"
  get "details", to: "static_pages#details"
  get "beta", to: "static_pages#beta"
  get "for-tenants", to: "static_pages#tenants"

  get "meter-setup", to: "billable_meters#configure"
  get "billable_meters/reload_configured_list", to: "billable_meters#reload_configured_list"

  get "stripe/connect", to:"accounts#stripe_callback", as: :stripe_connect

  resources :contacts
  resources :billable_meters
  resources :meters
  resources :invoices
  resources :tenants
  resources :records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/tenant_sign_up/:acct_id/:id", to: "tenants#sign_up"
  post "/accounts/:id/update_billing_day", to: "accounts#update_billing_day"  
  post "/accounts/:id/update_days_until_invoice_due", to: "accounts#update_days_until_invoice_due"
  resources :messages, only: [:new, :create]
  get "/signed_up", to: "messages#complete"
  get "/sign_up", to: "messages#new"
  post "/sign_up", to: "messages#create"
  
  #api
  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create, :show]
      resources :users, only: [:show] 
      get 'meters', to: 'users#meters'
      post 'meters', to: 'meters#import'
      post 'records', to: 'records#import'
      resources :billable_meters, only: [:index]
      resources :records, only: [:create]
    end
  end  
end

app/models/account.rb
class Account < ApplicationRecord
  has_one :site
  has_many :users
  has_many :tenants
  has_many :rates
  has_many :admin_costs
  has_many :billable_meters
  has_many :tenant_fees, dependent: :destroy

  def amount_overdue
    amount_overdue=0.0
    invoices.select{|i| i.status == "overdue"}.each do |invoice|
      amount_overdue += invoice.total
    end
    return amount_overdue
  end

  def amount_due
    total_due=0.0

    invoices.select{|i| i.status != "paid"}.each do |invoice|
        total_due+=invoice.total
    end
    return total_due
  end

  def amount_received
    total_received=0.0

    start_date = latest_billing_cycle_start_date

    invoices.select{|i| i.start_date == start_date}.each do |invoice|
      if (invoice.status=="paid")
        total_received+=invoice.total
      end
    end
    return total_received
  end

  def invoices
    invoices=Array.new
    self.tenants.each do |t|
      (invoices << t.invoices).flatten!
    end
    return invoices.sort_by(&:end_date).reverse
  end

  def billing_cycles
    ordered_invoices = self.invoices
    return ordered_invoices.group_by{|i| i.readable_date }.map
  end

  private
    def latest_billing_cycle_start_date
      billingCycles = self.billing_cycles
      if (billingCycles.any?)
        return billingCycles.first[1].first.start_date
      else
        return DateTime.now.beginning_of_month
      end
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :update_billing_day, :update_days_until_invoice_due, :stripe_callback]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    if current_user.tenant?
      redirect_to current_user
    else
      @account = current_user.account
    end
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
    @user = current_user
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    set_account_defaults

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_billing_day

    noticeText = ""
    billing_day = params[:billing_cycle_start_day]

    if (@account && billing_day != nil)
      @account.billing_cycle_start_day = billing_day
      @account.save
      noticeText = "The first day of your billing cycle is now set to the " + billing_day.to_i.ordinalize + " of the month."
    else
      noticeText = "There was a problem updating your billing cycle start date. Contact Apex for support"
    end
    redirect_back(fallback_location: root_path, notice: noticeText)
  end

  def update_days_until_invoice_due
    noticeText = ""
    days_until_due = params[:days_until_invoice_due]

    if (@account && days_until_due != nil)
      @account.days_until_invoice_due = days_until_due
      @account.save
      noticeText = "Your invoices will be due " + days_until_due + " days after they are sent."
    else
      noticeText = "There was a problem updating your invoice due date. Contact Apex for support"
    end
    redirect_back(fallback_location: root_path,notice: noticeText)
  end

  def stripe_callback
    options = {
      site: 'https://connect.stripe.com',
      authorize_url: '/oauth/authorize',
      token_url: '/oauth/token'
    }

    code = params[:code]
    client = OAuth2::Client.new(ENV['STRIPE_CONNECT_CLIENT_ID'], ENV['STRIPE_SECRET_KEY'], options)
    @resp = client.auth_code.get_token(code, :params => {:scope => 'read_write'})
    @access_token = @resp.token

    @account.update!(stripe_account_id: @resp.params["stripe_user_id"]) if @resp

    flash[:notice] = "Your account has been successfully created and is ready to process payments!"

    redirect_to edit_account_path(@account)
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      if (current_user)
        @account = current_user.account
      else
        redirect_to new_user_session_path
      end
    end

    def set_account_defaults
      if (@account.billing_cycle_start_day == nil)
        @account.billing_cycle_start_day = 1
      end
      
      if (@account.days_until_invoice_due == nil)
        @account.days_until_invoice_due = 20
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.fetch(:account, {})
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def stripe_connect_link
    stripe_url = "https://connect.stripe.com/express/oauth/authorize"
    client_id = ENV["STRIPE_CONNECT_CLIENT_ID"]

    "#{stripe_url}?client_id=#{client_id}"
  end

end

app/views/accounts/_billing_cycle_list.html.erb
<% i=0 %>
<div class="table">
  <% billing_cycles.drop(1).each do |date,invoices| %>
    <div class="table-row">
      <h4 data-toggle="collapse" data-target=".accordion-<%= i %>" class="text-center panel-heading clickable collapsed"><%= date %></h4>
    </div>      
    <div class="accordion-<%= i %> collapse">
      <%= render 'headered_invoices_list', invoices: invoices %>
    </div>
    <hr />
    <% i+=1 %>
  <% end %>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/_headered_invoices_list.html.erb
<% if invoices != nil %>

<%
    amount_overdue = 0.0
    amount_received = 0.0
    amount_due = 0.0
    invoices.each do |invoice|
      if (invoice.status == "paid")
        amount_received += invoice.total
      elsif (invoice.status != "paid")
        amount_due += invoice.total
      end
        
    end
  %>
      <div class="table-row-item"  style="display: flex;">
        <% column_width = 'col-md-4' %>
        
        <div class="col-md-2"></div>

        <div class="<%= column_width %> text-center">
          <span class="text-muted text-uppercase">amount received</span>
          <h3 class="large-currency">
            <sup>$</sup><%= '%.2f' % amount_received %>
          </h3>
        </div>

        <div class="<%= column_width %> text-center">
          <span class="text-muted text-uppercase">amount due</span>
          <h3 class="large-currency">
            <sup>$</sup><%= '%.2f' % amount_due %>
          </h3>
        </div>
          
        <div class="col-md-2"></div>
      </div>
      <hr />

  <%= render 'invoices_list', invoices: invoices %>

<% end %>

app/views/accounts/_invoices_list.html.erb
<% if invoices != nil %>
  <% invoices.each do |invoice| 
    number = invoice.number
    tenant_name = invoice.tenant.name
    amount = number_with_delimiter(number_to_currency(invoice.total),delimiter:',')
    status = invoice.status
    %>
    <div class="table-row-item clickable-row <%= (invoice.overdue ? 'overdue':'') %>" data-href='<%= invoice_path(invoice) %>'>
      <div class="col-2 table-cell"><%= number %></div>              
      <div class="col-6 table-cell"><%= tenant_name %></div>
      <div class="col-2 table-cell text-center"><%= amount %></div>
      <div class="col-2 table-cell text-center"><%= status %></div>
    </div>
  <% end %>
<% end %>

app/views/accounts/edit.html.erb
<div class="row">
  <div class="offset-2 col-8 text-center">
    <h2>Your Account</h2>
    <hr>    
    <br />
  </div>
</div>

<div class="row" id="settings">

  <div class="offset-2 col-4 text-left">
    <% if !current_user.tenant? %>
      <%= form_tag "update_billing_day", method: :post do %>
        <% current_cycle_start_day = current_account.billing_cycle_start_day ? current_account.billing_cycle_start_day : 1 
        %>
        <div class="input-group">
          <div class="select-label">Update your billing cycle start date:</div>
          <%= select_tag(:billing_cycle_start_day, options_for_select(1..31, current_cycle_start_day), id: "billing-cycle-select") %>
          <%= submit_tag "Update", class: "btn btn-primary" %>
        </div>
      <% end %>
      <p/>
      <%= form_tag "update_days_until_invoice_due", method: :post do %>
        <% current_cycle_start_day = current_account.days_until_invoice_due ? current_account.days_until_invoice_due : 20 
        %>
        <div class="input-group">
          <div class="select-label">Number of days to pay:</div>
          <%= select_tag(:days_until_invoice_due, options_for_select((20..60).step(5), current_cycle_start_day), id: "billing-cycle-select") %>
          <%= submit_tag "Update", class: "btn btn-primary" %>
        </div>
        <p/>        
      <% end %>
      <span class="font-italic">Your invoices will be available when we recieve data for the <%= @account.billing_cycle_start_day.ordinalize %>, and will be due <%= @account.days_until_invoice_due %> days later.</span>
      </br>
      </br>
      <hr>
      <p>ELLY uses <a href="https://stripe.com">Stripe</a> to process invoices and send payments to account managers.</p>
      <div>
        <h5 class="float-left" style="padding-top: 8px;">Payment Account Status:</h5>

        <% if current_account.stripe_account_id.nil? %>
          <span class="glyphicon glyphicon-remove float-left" style="padding-left: 15px; padding-top: 11px"></span>
          <a class="btn btn-outline-primary float-right" role="button" aria-pressed="true" href="https://connect.stripe.com/express/oauth/authorize?response_type=code&client_id=<%= ENV['STRIPE_CONNECT_CLIENT_ID'] %>&scope=read_write">
            Set Up Payouts
          </a>
        <% else %>
          <span class="glyphicon glyphicon-ok float-left" style="padding-left: 15px; padding-top: 8px"></span>
          <span class="float-left" style="padding-left: 15px; padding-top: 8px">Connected</span>
        <% end %>
      </div>
    <% else %>
      <% if current_user.stripe_token.nil? %>
        <%= render "banks/new" %>
      <% elsif !current_user.payments_verified
        customer = Stripe::Customer.retrieve(current_user.stripe_token)
        bank_account = customer.sources.data.first.id %>
        <%= render "microdeposits/new", customer: customer.id, bank_account: bank_account %>
      <% else %>
        <h3>Bank verified.</h3>
      <% end %>
    <% end %>
  </div>

  <div class="col-4">
    <%= render :template => 'devise/registrations/edit' %>
  </div>
</div>

<script type="text/javascript">
  jQuery(document).ready(function($) { 
    $('select#billing-cycle-select').select2({
      theme: "bootstrap",
      allowClear: false,
      dropdownParent: $("#settings"),
      minimumResultsForSearch: 100,
      width: 60
    });
  });
</script>

app/views/accounts/eula.html.erb
<div class="row">
  <div class="offset-md-2 col-8">
    
    <h2>End-User License Agreement (EULA) of <span class="app_name">ELLY</span></h2>

    <p>This End-User License Agreement ("EULA") is a legal agreement between you and <span class="company_name">Apex Custom Solutions, LLC</span></p>

    <p>This EULA agreement governs your acquisition and use of our <span class="app_name">ELLY</span> software ("Software") directly from <span class="company_name">Apex Custom Solutions, LLC</span> or indirectly through a <span class="company_name">Apex Custom Solutions, LLC</span> authorized reseller or distributor (a "Reseller").</p>

    <p>Please read this EULA agreement carefully before completing the installation process and using the <span class="app_name">ELLY</span> software. It provides a license to use the <span class="app_name">ELLY</span> software and contains warranty information and liability disclaimers.</p>

    <p>If you register for a free trial of the <span class="app_name">ELLY</span> software, this EULA agreement will also govern that trial. By clicking "accept" or installing and/or using the <span class="app_name">ELLY</span> software, you are confirming your acceptance of the Software and agreeing to become bound by the terms of this EULA agreement.</p>

    <p>If you are entering into this EULA agreement on behalf of a company or other legal entity, you represent that you have the authority to bind such entity and its affiliates to these terms and conditions. If you do not have such authority or if you do not agree with the terms and conditions of this EULA agreement, do not install or use the Software, and you must not accept this EULA agreement.</p>

    <p>This EULA agreement shall apply only to the Software supplied by <span class="company_name">Apex Custom Solutions, LLC</span> herewith regardless of whether other software is referred to or described herein. The terms also apply to any <span class="company_name">Apex Custom Solutions, LLC</span> updates, supplements, Internet-based services, and support services for the Software, unless other terms accompany those items on delivery. If so, those terms apply.

    <h3>License Grant</h3>

    <p><span class="company_name">Apex Custom Solutions, LLC</span> hereby grants you a personal, non-transferable, non-exclusive licence to use the <span class="app_name">ELLY</span> software on your devices in accordance with the terms of this EULA agreement.</p>

    <p>You are permitted to load the <span class="app_name">ELLY</span> software (for example a PC, laptop, mobile or tablet) under your control. You are responsible for ensuring your device meets the minimum requirements of the <span class="app_name">ELLY</span> software.</p>

    <p>You are not permitted to:</p>

    <ul>
    <li>Edit, alter, modify, adapt, translate or otherwise change the whole or any part of the Software nor permit the whole or any part of the Software to be combined with or become incorporated in any other software, nor decompile, disassemble or reverse engineer the Software or attempt to do any such things</li>
    <li>Reproduce, copy, distribute, resell or otherwise use the Software for any commercial purpose</li>
    <li>Allow any third party to use the Software on behalf of or for the benefit of any third party</li>
    <li>Use the Software in any way which breaches any applicable local, national or international law</li>
    <li>Use the Software for any purpose that <span class="company_name">Apex Custom Solutions, LLC</span> considers is a breach of this EULA agreement</li>
    </ul>

    <h3>Intellectual Property and Ownership</h3>

    <p><span class="company_name">Apex Custom Solutions, LLC</span> shall at all times retain ownership of the Software as originally downloaded by you and all subsequent downloads of the Software by you. The Software (and the copyright, and other intellectual property rights of whatever nature in the Software, including any modifications made thereto) are and shall remain the property of <span class="company_name">Apex Custom Solutions, LLC</span>.</p>

    <p><span class="company_name">Apex Custom Solutions, LLC</span> reserves the right to grant licences to use the Software to third parties.</p>

    <h3>Termination</h3>

    <p>This EULA agreement is effective from the date you first use the Software and shall continue until terminated. You may terminate it at any time upon written notice to <span class="company_name">Apex Custom Solutions, LLC</span>.</p>

    <p>It will also terminate immediately if you fail to comply with any term of this EULA agreement. Upon such termination, the licenses granted by this EULA agreement will immediately terminate and you agree to stop all access and use of the Software. The provisions that by their nature continue and survive will survive any termination of this EULA agreement.</p>

    <h3>Governing Law</h3>

    <p>This EULA agreement, and any dispute arising out of or in connection with this EULA agreement, shall be governed by and construed in accordance with the laws of <span class="country">us</span>.</p>
    
    </br>
  </div>
</div>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<h1 class="text-center">Account Totals</h1>
<div class="row">
  <div class="offset-md-2 col-8">
    <br>
    <div class="row">
      <% column_width = 'col-md-4'
      if @account.amount_overdue > 0  %>
          <div class="<%= column_width %> text-center">
            <%= link_to invoices_path(:status => :overdue) do %>
              <span class="text-muted text-uppercase">amount overdue</span>
            <% end %>
              <h3 class="large-currency text-danger">
                <sup>$</sup><%= '%.2f' % @account.amount_overdue %>
              </h3>
          </div>
      <% else %>
        <div class="offset-2"></div>
      <% end %>

      <div class="<%= column_width %> text-center">
        <span class="text-muted text-uppercase">amount received (last period)</span>
        <h3 class="large-currency">
          <sup>$</sup><%= '%.2f' % @account.amount_received %>
        </h3>
      </div>
      <div class="<%= column_width %> text-center">
        <span class="text-muted text-uppercase">amount due</span>
        <h3 class="large-currency">
          <sup>$</sup><%= '%.2f' % @account.amount_due %>
        </h3>
      </div>
    </div>
    <br>
  </div>
</div>
<hr />

<br>
<br>


<% billing_cycles = @account.billing_cycles %>
<% if (billing_cycles.any?) %>
  <% date,invoices = billing_cycles.first %>
  <%
    amount_overdue = 0.0
    amount_received = 0.0
    amount_due = 0.0
    invoices.each do |invoice|
      if (invoice.status == "paid")
        amount_received += invoice.total
      elsif (invoice.status != "paid")
        amount_due += invoice.total
      end
        
    end
  %>
  <!-- <h5 class="text-center text-muted "><%= date %> at a glance...</h5> -->
  <!-- <p class="text-center text-muted text-uppercase"><%= date %></p> -->
  <div class="row">
      <div class="offset-md-2 col-8">
        <h2 class="text-center"><%= date %></h2>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="offset-md-2 col-8">
        
        <div class="row">
          <% column_width = 'col-md-4' %>
            
          <div class="offset-2"></div>

          <div class="<%= column_width %> text-center">
            <span class="text-muted text-uppercase">amount received</span>
            <h3 class="large-currency">
              <sup>$</sup><%= '%.2f' % amount_received %>
            </h3>
          </div>
          <div class="<%= column_width %> text-center">
            <span class="text-muted text-uppercase">amount due</span>
            <h3 class="large-currency">
              <sup>$</sup><%= '%.2f' % amount_due %>
            </h3>
          </div>
        </div>
        <hr />
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="table">
          <div class="table-row">  
            <div class="table-row-grouping">
              <%= render 'invoices_list', invoices: invoices %>
            </div>
          </div>
        </div>
      </div>
    </div>
  
<% end %>
</br>
</br>

<div class="light-gray">
  </br>
  <h3 class="text-center">Previous Months</h3>
  </br>
  <div class="row">
    <div id="billing-cycles" class="col-10 col-md-8 offset-md-2">
      </br>
      <%= render 'billing_cycle_list', billing_cycles: billing_cycles %>
    </div>
  </div>

</div>